from .MainWindow import MainWindow
from .AdminWindow import AdminWindow
from .ChangeInforForm import ChangeInforForm
from .DetailsDialog import DetailsDialog
from .FaceRegWindow import FaceRegWindow
from .IdPassWindow import IdPassWindow
from .PasswordForm import PasswordForm
from .FaceForm import FaceForm
from .InformationsForm import InformationsForm
from .AdminForm import AdminForm
from .StatusForm import StatusForm
from .SecretKeyForm import SecretKeyForm