from .Ui_MainWindow import Ui_MainWindow
from .FaceRegWindow import Ui_FaceRegWindow
from .IdPassWindow import Ui_IdPassWindow
from .DetailsDialog import Ui_DetailsDialog
from .AdminWindow import Ui_AdminWindow
from .Ui_PasswordForm import Ui_PasswordForm
from .Ui_ChangeInforForm import Ui_ChangeInforForm
from .Ui_FaceForm import Ui_FaceForm
from .Ui_InformationsForm import Ui_InformationsForm
from .Ui_AdminForm import Ui_AdminForm
from .Ui_StatusForm import Ui_StatusForm
from .Ui_StatusDialog import Ui_StatusDialog
from .Ui_SecretKeyForm import Ui_SecretKeyForm